### ISSUE TITLE
Custom Paintings looking for Zip File only Texture Packs (Bibliocraft 1.9.2)

### ISSUE THREAD

**Issue by Megistus** [Nuchaz/BiblioCraft#224]
While this issue does not (apparently) effect game loading or play, it does throw error codes out during load and requires that a texture pack be zipped. As I am constantly tinkering with textures, especially for mod support for Glimmar's Steampunk, I usually need to have my texture packs open.

If you would be so kind as to modify your code so that it looks for both zipped and unzipped texture packs, it would be greatly appreciated.

Error during game load:
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: /Users/~~/Library/Application Support/minecraft/resourcepacks/Mod_Support_for_GlimmarsSteampunk[1.7.10] (Is a directory)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.open(Native Method)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.getListFromResourcePack(PaintingUtil.java:306)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.getResourcePackPaintings(PaintingUtil.java:256)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.getListOfPaintings(PaintingUtil.java:140)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.updateCustomArtDatas(PaintingUtil.java:62)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.EventResourcePackReload.ReloadResourcePackEvent(EventResourcePackReload.java:11)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_EventResourcePackReload_ReloadResourcePackEvent_Post.invoke(.dynamic)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:276)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reflector.callVoid(Reflector.java:190)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:398)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:123)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:200)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:151)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:158)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.FileNotFoundException: /Users/christopherlehr/Library/Application Support/minecraft/resourcepacks/Third Party (Is a directory)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.open(Native Method)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.getListFromResourcePack(PaintingUtil.java:306)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.getResourcePackPaintings(PaintingUtil.java:256)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.getListOfPaintings(PaintingUtil.java:140)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.PaintingUtil.updateCustomArtDatas(PaintingUtil.java:62)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at jds.bibliocraft.EventResourcePackReload.ReloadResourcePackEvent(EventResourcePackReload.java:11)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_EventResourcePackReload_ReloadResourcePackEvent_Post.invoke(.dynamic)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:276)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reflector.callVoid(Reflector.java:190)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:398)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:123)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:200)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:151)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:158)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[07:21:31] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Nuchaz** [comment]
Ah, I guess I never anticipated packs that weren't zipped. I'll put some time into that when I can and make sure I check if something is a zip before trying to do stuff with it (to prevent those errors) and see about scanning folders if a folder is found instead.

**Comment by Nuchaz** [comment]
I got a fix for this in code so it will scan folders as well as zip files and no longer throws the error code. This will be included in the next release for MC 1.7.10.
