### ISSUE TITLE
Client crash with a BiblioCraft painting

### ISSUE THREAD

**Issue by iskall85** [Nuchaz/BiblioCraft#314]
Hi

After putting down a painting from BiblioCraft the client crashes every time that chunk is loaded (observe, the server does not crash). Seems to be a rendering issue.

The pack uses BiblioCraft 1.9.2 for Minecraft 1.7.10
Before updating Id like to see if this is known. I Couldnt find any old bug report of this on here.

Crash Report:
http://pastebin.com/JekDkeB2

Google Search Lines of the crash report (to ease for others)
java.lang.ArrayIndexOutOfBoundsException: 2
        at jds.bibliocraft.rendering.TileEntityPaintingRenderer.func_147500_a(TileEntityPaintingRenderer.java:257)
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
        at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
        at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
        at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
        at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)

Thanks for having a look!

**Comment by Nuchaz** [comment]
This was fixed in v1.10.4. There was a bug that prevented information on a painting frame to be retained instead of reset when a painting was removed, so if you added another painting and the old info on the painting frame was incompatible, you crashed. I think that is what is happening here.
