### ISSUE TITLE
Crash with TerraFirmaCraft 0.79.29.922

### ISSUE THREAD

**Issue by Baughn** [Nuchaz/BiblioCraft#364]
I think you've seen this before, and it was a few versions ago, so I'm not sure why it's back. To be more precise, this crash happens with BiblioWoods-1.2-TerraFirmaCraftV0.79.23.jar, not BiblioCraft base.

```
java.lang.NullPointerException: Exception in server tick loop
    at com.bioxx.tfc.Core.TFC_Core.getSuperSeed(TFC_Core.java:1381)
    at com.bioxx.tfc.api.Crafting.AnvilRecipe.<init>(AnvilRecipe.java:31)
    at jds.bibliowood.tfcwood.WoodsLoader.initAnvilRecipies(WoodsLoader.java:346)
    at jds.bibliowood.tfcwood.AnvilRecipeHandler.onLoadWorld(AnvilRecipeHandler.java:18)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_259_AnvilRecipeHandler_onLoadWorld_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Full crash log: http://sprunge.us/KSCe

**Comment by Baughn** [comment]
This turned out to depend on the order in which mods are loaded, as by filename.

That's probably still a bug.
