### ISSUE TITLE
Server crash at startup with Bibliocraft 2.0.1

### ISSUE THREAD

**Issue by quenti123** [Nuchaz/BiblioCraft#385]
Hi Nuchaz,

I am still getting error and crash when my server is loading... I installed Bibliocraft 2.0.1 and my serveur is running with forge-1.8.9-11.15.1.1890
I also tried with forge 11.15.1.1722 with the same problem :(

Here is the error message I get from the server console :

> [10:48:51] [Server thread/ERROR] [FML]: A TileEntity type jds.bibliocraft.tileentities.BiblioLightTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
> java.lang.NullPointerException
> 
> at jds.bibliocraft.tileentities.BiblioLightTileEntity.writeCustomNBTData(BiblioLightTileEntity.java:51) ~[BiblioLightTileEntity.class:?]
> 
> at jds.bibliocraft.tileentities.BiblioTileEntity.writeNBTData(BiblioTileEntity.java:468) ~[BiblioTileEntity.class:?]
> 
> at jds.bibliocraft.tileentities.BiblioTileEntity.func_145841_b(BiblioTileEntity.java:436) ~[BiblioTileEntity.class:?]
> 
> at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:368) [anj.class:?]
> 
> at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:165) [anj.class:?]
> 
> at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:238) [ld.class:?]
> 
> at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:298) [ld.class:?]
> at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:905) [le.class:?]
> 
> at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366) [MinecraftServer.class:?]
> 
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:628) [MinecraftServer.class:?]
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
> 
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
> [10:48:51] [Server thread/ERROR] [FML]: A TileEntity type jds.bibliocraft.tileentities.BiblioLightTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
> java.lang.NullPointerException
> 
> at jds.bibliocraft.tileentities.BiblioLightTileEntity.writeCustomNBTData(BiblioLightTileEntity.java:51) ~[BiblioLightTileEntity.class:?]
> 
> at jds.bibliocraft.tileentities.BiblioTileEntity.writeNBTData(BiblioTileEntity.java:468) ~[BiblioTileEntity.class:?]
> 
> at jds.bibliocraft.tileentities.BiblioTileEntity.func_145841_b(BiblioTileEntity.java:436) ~[BiblioTileEntity.class:?]
> 
> at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:368) [anj.class:?]
> 
> at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:165) [anj.class:?]
> 
> at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:238) [ld.class:?]
> 
> at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:298) [ld.class:?]
> 
> at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:905) [le.class:?]
> 
> at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366) [MinecraftServer.class:?]
> 
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:628) [MinecraftServer.class:?]
> 
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
> 
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

And this message is reapeating over and over again... Could you tell me whats wrong ?

**Comment by quenti123** [comment]
Ok so I figured it out by myself.....

In case anyone has the same problem, I was using forge-1.8.9-11.15.1.1890 and it didn't work

But when i tried with forge 11.15.1.1902, it worked :)
