### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by runefoust** [Nuchaz/BiblioCraft#427]
here's the crash report. I've never done this before, so please let me know if there's something else you need.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/11/17 11:25 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tinkers Alloying Addon (taiga)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at com.sosnitzka.taiga.recipes.SmeltingRegistry.register(SmeltingRegistry.java:15)
	at com.sosnitzka.taiga.TAIGA.init(TAIGA.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1891439800 bytes (1803 MB) / 6162903040 bytes (5877 MB) up to 10093199360 bytes (9625 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn6G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UCHI	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCHI	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4.jar) 
	UCHI	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHI	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2].jar) 
	UCHI	BiomesOPlenty{5.0.0.2155} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar) 
	UCHI	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHI	Botania{r1.9-340} [Botania] (Botania r1.9-340.jar) 
	UCHI	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHI	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHI	dungeontactics{DT-0.11.1} [DungeonTactics] (DungeonTactics-1.10.2-0.11.1.jar) 
	UCHI	eplus{4.1.0.113} [Enchanting Plus] (EnchantingPlus-1.10.2-4.1.0.115.jar) 
	UCHI	golems{6.02} [Extra Golems] (ExtraGolems[1.10.2]-6.02.jar) 
	UCHI	gyth{2.0.0.2} [Get Ya' Tanks Here] (Gyth-1.10.2-2.0.0.23.jar) 
	UCHI	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHI	JEI{3.14.5.406} [Just Enough Items] (jei_1.10.2-3.14.5.406.jar) 
	UCHI	ironbackpacks{1.10.2-2.2.23} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.23.jar) 
	UCHI	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHI	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHI	minecolonies{1.10.2-0.6.2991} [MineColonies] (minecolonies-universal-1.10.2-0.6.2991.jar) 
	UCHI	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHI	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHI	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHI	Roguelike{1.5.6} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.6.jar) 
	UCHI	roots{0.109} [Roots] (roots-1.10.2-0.109.0.jar) 
	UCHI	RuinsAndConstructs{1.0.4} [RuinsAndConstructs] (Ruins And Constructs (v1.0.4).jar) 
	UCHI	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHE	taiga{1.1.4} [Tinkers Alloying Addon] (taiga-1.10.2-1.1.4.jar) 
	UCHI	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHI	tinker_io{release 2.4.3} [Tinker I/O] (tinker_io-1.10.2-release 2.4.3.jar) 
	UCHI	TinkersAddons{1.0.4} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.4.jar) 
	UCHI	golems_tcon{6.02.1} [Tinkers' Golems Addon] (TinkersGolemsAddon[1.10.2]-6.02.1.jar) 
	UCHI	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHI	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	Loaded coremods (and transformers): 
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4531' Renderer: 'Intel(R) HD Graphics 4600'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

**Comment by Ravin890** [comment]
The mod causing crash isn't bibliocraft, its taiga

**Comment by Nuchaz** [comment]
This is unrelated to BiblioCraft.
