### ISSUE TITLE
[1.11.2] Tesselating block crash when using tape measure on sandstone with Optifine's connected textures enabled

### ISSUE THREAD

**Issue by gryttr** [Nuchaz/BiblioCraft#465]
If you place the tape measure's marker pole on sandstone and you have Optifine's connected textures enabled, the game will crash with a tesselating block model exception. The world will continue to crash on load, but can be successfully loaded by turning off Optifine's connected textures from the main menu.

Bibliocraft version: 2.3.1
Optifine version: 1.11.2_HD_U_C1
Forge version: 13.20.0.2299

<details>
<summary>Crash report</summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/4/17 7:19 AM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.buildQuads(OBJModel.java:1343)
	at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.func_188616_a(OBJModel.java:1312)
	at jds.bibliocraft.models.ModelMarkerPole.func_188616_a(ModelMarkerPole.java:227)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1377)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1323)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1303)
	at ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1695)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:545)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:108)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:54)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:173)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1438)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1700)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1361)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.buildQuads(OBJModel.java:1343)
	at net.minecraftforge.client.model.obj.OBJModel$OBJBakedModel.func_188616_a(OBJModel.java:1312)
	at jds.bibliocraft.models.ModelMarkerPole.func_188616_a(ModelMarkerPole.java:227)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1377)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1323)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1303)
	at ConnectedTextures.getConnectedTextureTop(ConnectedTextures.java:1695)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:545)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:108)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)

-- Block model being tesselated --
Details:
	Block: minecraft:sandstone[type=sandstone]
	Block location: World: (96,68,264), Chunk: (at 0,4,8 in 6,16; contains blocks 96,0,256 to 111,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:74)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:54)

-- Block being tesselated --
Details:
	Block type: ID #24 (tile.sandStone // net.minecraft.block.BlockSandStone)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (96,68,264), Chunk: (at 0,4,8 in 6,16; contains blocks 96,0,256 to 111,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:296)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:173)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1438)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1700)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1590)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['HeimrArnadalr'/1590, l='MpServer', x=96.00, y=68.00, z=262.92]]
	Chunk stats: MultiplayerChunkCache: 491, 491
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (92,64,256), Chunk: (at 12,4,0 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 313 game time, 313 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntitySheep['Sheep'/58, l='MpServer', x=19.50, y=92.00, z=212.50], EntitySheep['Sheep'/59, l='MpServer', x=18.50, y=91.00, z=212.50], EntitySheep['Sheep'/60, l='MpServer', x=19.50, y=93.00, z=210.50], EntitySheep['Sheep'/61, l='MpServer', x=22.50, y=94.00, z=209.50], EntitySheep['Sheep'/62, l='MpServer', x=23.50, y=103.00, z=293.50], EntitySheep['Sheep'/63, l='MpServer', x=23.82, y=102.00, z=291.37], EntitySheep['Sheep'/64, l='MpServer', x=20.50, y=98.00, z=286.50], EntitySheep['Sheep'/65, l='MpServer', x=20.50, y=98.00, z=287.50], EntityItem['item.tile.mushroom'/84, l='MpServer', x=46.88, y=60.00, z=232.78], EntityChicken['Chicken'/85, l='MpServer', x=52.50, y=93.00, z=315.50], EntityChicken['Chicken'/86, l='MpServer', x=51.50, y=94.00, z=318.50], EntityChicken['Chicken'/87, l='MpServer', x=51.50, y=93.00, z=314.50], EntityChicken['Chicken'/88, l='MpServer', x=53.50, y=93.00, z=314.50], EntitySheep['Sheep'/103, l='MpServer', x=96.50, y=85.00, z=321.50], EntitySheep['Sheep'/104, l='MpServer', x=93.50, y=88.00, z=321.50], EntitySheep['Sheep'/105, l='MpServer', x=91.50, y=91.00, z=319.50], EntitySheep['Sheep'/106, l='MpServer', x=89.50, y=90.00, z=321.50], EntitySheep['Sheep'/115, l='MpServer', x=117.75, y=66.00, z=230.36], EntitySheep['Sheep'/116, l='MpServer', x=115.41, y=66.00, z=229.50], EntitySheep['Sheep'/117, l='MpServer', x=118.45, y=66.00, z=228.19], EntitySheep['Sheep'/118, l='MpServer', x=114.45, y=66.00, z=229.50], EntityPig['Pig'/119, l='MpServer', x=113.50, y=60.00, z=255.50], EntityPig['Pig'/120, l='MpServer', x=116.50, y=59.00, z=257.50], EntityPig['Pig'/121, l='MpServer', x=105.53, y=68.00, z=263.25], EntityPig['Pig'/122, l='MpServer', x=112.50, y=68.00, z=261.50], EntitySheep['Sheep'/123, l='MpServer', x=114.26, y=70.00, z=273.55], EntitySheep['Sheep'/124, l='MpServer', x=112.54, y=69.00, z=269.55], EntitySheep['Sheep'/125, l='MpServer', x=118.51, y=69.00, z=277.71], EntitySheep['Sheep'/126, l='MpServer', x=109.38, y=70.00, z=273.74], EntityCow['Cow'/127, l='MpServer', x=114.33, y=69.00, z=267.45], EntityCow['Cow'/128, l='MpServer', x=115.50, y=69.00, z=266.50], EntityCow['Cow'/129, l='MpServer', x=113.92, y=69.00, z=268.81], EntityCow['Cow'/130, l='MpServer', x=113.45, y=69.00, z=267.90], EntitySheep['Sheep'/131, l='MpServer', x=126.42, y=69.00, z=257.77], EntitySheep['Sheep'/132, l='MpServer', x=127.03, y=69.00, z=258.95], EntitySheep['Sheep'/133, l='MpServer', x=119.74, y=69.00, z=262.40], EntitySheep['Sheep'/134, l='MpServer', x=122.60, y=69.00, z=266.22], EntitySheep['Sheep'/143, l='MpServer', x=137.50, y=70.00, z=190.50], EntitySheep['Sheep'/144, l='MpServer', x=138.50, y=70.00, z=192.50], EntitySheep['Sheep'/145, l='MpServer', x=141.50, y=72.00, z=193.50], EntitySheep['Sheep'/146, l='MpServer', x=142.50, y=72.00, z=195.50], EntityBat['Bat'/4319, l='MpServer', x=159.54, y=30.97, z=285.52], EntityBat['Bat'/4321, l='MpServer', x=84.53, y=16.84, z=184.66], EntityZombie['Zombie'/4681, l='MpServer', x=63.50, y=26.00, z=339.75], EntityBat['Bat'/4690, l='MpServer', x=140.49, y=18.00, z=319.84], EntitySquid['Squid'/4701, l='MpServer', x=48.41, y=60.84, z=276.95], EntitySquid['Squid'/4702, l='MpServer', x=50.22, y=59.46, z=271.79], EntitySquid['Squid'/4718, l='MpServer', x=47.27, y=61.94, z=274.84], EntitySquid['Squid'/4719, l='MpServer', x=51.60, y=61.35, z=277.73], EntityZombie['Zombie'/4826, l='MpServer', x=89.50, y=19.00, z=273.50], EntityZombie['Zombie'/4827, l='MpServer', x=89.50, y=19.00, z=273.50], EntityZombie['Zombie'/4836, l='MpServer', x=34.50, y=49.00, z=261.50], EntityBat['Bat'/4892, l='MpServer', x=113.42, y=60.10, z=301.25], EntityBat['Bat'/4927, l='MpServer', x=114.95, y=59.34, z=250.81], EntityBat['Bat'/4942, l='MpServer', x=30.36, y=34.13, z=260.32], EntityBat['Bat'/4944, l='MpServer', x=57.78, y=16.98, z=270.81], EntityBat['Bat'/4945, l='MpServer', x=45.37, y=18.74, z=248.33], EntityBat['Bat'/4953, l='MpServer', x=108.45, y=30.89, z=328.51], EntityBat['Bat'/4981, l='MpServer', x=145.69, y=14.77, z=300.47], EntityBat['Bat'/4982, l='MpServer', x=144.57, y=21.28, z=301.86], EntityBat['Bat'/5031, l='MpServer', x=128.88, y=50.03, z=248.37], EntitySkeleton['Skeleton'/5081, l='MpServer', x=155.50, y=22.00, z=282.50], EntityBat['Bat'/5092, l='MpServer', x=169.91, y=31.04, z=228.20], EntityCreeper['Creeper'/5126, l='MpServer', x=44.50, y=16.00, z=340.50], EntityZombie['Zombie'/5127, l='MpServer', x=43.50, y=16.00, z=340.50], EntityCreeper['Creeper'/5138, l='MpServer', x=97.50, y=32.00, z=272.50], EntitySkeleton['Skeleton'/5170, l='MpServer', x=82.50, y=16.00, z=321.50], EntitySkeleton['Skeleton'/5171, l='MpServer', x=90.50, y=16.00, z=324.50], EntitySkeleton['Skeleton'/5174, l='MpServer', x=140.50, y=23.00, z=263.50], EntitySkeleton['Skeleton'/5193, l='MpServer', x=58.05, y=32.00, z=334.45], EntityZombie['Zombie'/5201, l='MpServer', x=76.50, y=25.00, z=313.50], EntitySkeleton['Skeleton'/5202, l='MpServer', x=78.50, y=25.00, z=316.50], EntitySkeleton['Skeleton'/5205, l='MpServer', x=34.50, y=50.00, z=252.50], EntityCreeper['Creeper'/5207, l='MpServer', x=35.50, y=50.00, z=252.50], EntityCreeper['Creeper'/5208, l='MpServer', x=34.50, y=50.00, z=254.50], EntityCreeper['Creeper'/5209, l='MpServer', x=35.50, y=50.00, z=253.50], EntityCreeper['Creeper'/5221, l='MpServer', x=109.50, y=16.00, z=325.50], EntityCreeper['Creeper'/5223, l='MpServer', x=117.48, y=30.00, z=328.20], EntityCreeper['Creeper'/5242, l='MpServer', x=143.13, y=35.00, z=312.88], EntityZombie['Zombie'/5256, l='MpServer', x=96.50, y=45.00, z=230.50], EntityZombie['Zombie'/5257, l='MpServer', x=97.50, y=45.00, z=228.50], EntityCreeper['Creeper'/5258, l='MpServer', x=96.50, y=45.00, z=233.50], EntitySkeleton['Skeleton'/5262, l='MpServer', x=51.50, y=44.00, z=338.50], EntityZombieVillager['Zombie Villager'/5388, l='MpServer', x=119.50, y=51.00, z=245.50], EntityZombie['Zombie'/5507, l='MpServer', x=63.20, y=31.00, z=340.44], EntityItem['item.tile.doublePlant.paeonia'/5519, l='MpServer', x=141.78, y=66.00, z=232.97], EntityItem['item.tile.doublePlant.paeonia'/5521, l='MpServer', x=140.37, y=66.00, z=229.59], EntityItem['item.tile.flower1.dandelion'/5524, l='MpServer', x=70.13, y=62.00, z=274.73], EntityItem['item.item.seeds'/5525, l='MpServer', x=69.68, y=64.00, z=276.23], EntityCreeper['Creeper'/5532, l='MpServer', x=110.50, y=27.00, z=308.50], EntityCreeper['Creeper'/5533, l='MpServer', x=111.50, y=27.00, z=308.50], EntityItem['item.item.seeds'/5537, l='MpServer', x=92.33, y=68.00, z=237.33], EntityPlayerSP['HeimrArnadalr'/1590, l='MpServer', x=96.00, y=68.00, z=262.92], EntityCreeper['Creeper'/3652, l='MpServer', x=87.50, y=35.00, z=299.50], EntityZombie['Zombie'/3653, l='MpServer', x=90.50, y=35.00, z=297.50], EntityZombie['Zombie'/3654, l='MpServer', x=89.50, y=35.00, z=301.50], EntitySquid['Squid'/3858, l='MpServer', x=75.11, y=62.05, z=291.47], EntitySquid['Squid'/3859, l='MpServer', x=72.26, y=59.81, z=294.51], EntitySquid['Squid'/3860, l='MpServer', x=76.85, y=58.90, z=294.17], EntitySquid['Squid'/3861, l='MpServer', x=71.15, y=58.02, z=294.17]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 285947592 bytes (272 MB) / 693768192 bytes (661 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2299 Optifine OptiFine_1.11.2_HD_U_C1 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2299.jar) 
	UCHIJAAAA	forge{13.20.0.2299} [Minecraft Forge] (forge-1.11.2-13.20.0.2299.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAA	bibliocraft{2.3.1} [BiblioCraft] (BiblioCraft[v2.3.1][MC1.11.2].jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4542' Renderer: 'Intel(R) HD Graphics 530'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2299
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4542, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_C1
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4542
	OpenGlRenderer: Intel(R) HD Graphics 530
	OpenGlVendor: Intel
	CpuCount: 8
</details>

**Comment by Nuchaz** [comment]
This might be related to #466 #455 #463 #461 
Thanks for figuring out that your crash is casued by the connected textures option. Maybe that is related to what is happening on the other crashes. It looks like the same stuff in the report.  We might be onto something here.

**Comment by Nuchaz** [comment]
I thought I had this one, and I just tested again, after the latest release and it crashed on me. So this is still an issue. Will try to have it fixed for next release.

**Comment by Foxgreat** [comment]
Got same problem on my modpack
MC 1.12.2
Bibliocraft v2.4.3
Forge 2529
Optifine HD_U_C6
Minecraft sends crash to this model
at jds.bibliocraft.models.ModelMarkerPole.func_188616_a(ModelMarkerPole.java:225)

Hole crashlog you can see here
[crash_me_log.txt](https://github.com/Nuchaz/BiblioCraft/files/1453504/crash_me_log.txt)
