### ISSUE TITLE
RuntimeException: class jds.bibliocraft.tileentities.TileEntityShelf

### ISSUE THREAD

**Issue by Nitrama** [Nuchaz/BiblioCraft#538]
`[19:09:27] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.RuntimeException: class jds.bibliocraft.tileentities.TileEntityShelf is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_189516_d(TileEntity.java:78) ~[avj.class:?]
	at net.minecraft.tileentity.TileEntity.func_189517_E_(TileEntity.java:205) ~[avj.class:?]
	at jds.bibliocraft.tileentities.BiblioTileEntity.func_189517_E_(BiblioTileEntity.java:451) ~[BiblioTileEntity.class:?]
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52) ~[je.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187278_c(PlayerChunkMapEntry.java:175) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187276_a(PlayerChunkMapEntry.java:74) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:152) ~[ou.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227) ~[oo.class:?]
	at WorldServerOF.func_72835_b(WorldServerOF.java:37) ~[WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
	... 4 more`

**Comment by EvilDylan** [comment]
What circumstances cause this crash; placing a shelf or logging into a world with a shelf?
Do you have any more mods present?

**Comment by Nuchaz** [comment]
I think this was an issue with where I registered my tileentities. I think I've got it fixed and you can expect a fix in the next release, which will be 2.4.4 for MC 1.12.2.
