### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by fcpwiz** [Nuchaz/BiblioCraft#601]
This stacktrace gets spammed in my console: https://gist.github.com/fcpwiz/2c87568161c9be320fbc9f7f3b161374

**Comment by enricotagliavini** [comment]
Same here.

```
[21:56:46] [Server thread/FATAL] [VF]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityToolRack.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_191]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityToolRack.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at jds.bibliocraft.tileentities.TileEntityToolRack.getStackInSlot(TileEntityToolRack.java) ~[TileEntityToolRack.class:?]
        at com.rwtema.extrautils2.crafting.Radar$PacketPing.lambda$doStuffServer$1(Radar.java:185) ~[Radar$PacketPing.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more
```

Bibliocraft version 2.4.5
Forge 1.12.2-14.23.5.2768
Multi player vanilla server + forge (not sponge or the like).

Possibly triggered by extrautils2?
