### ISSUE TITLE
Parsing error loading recipe bibliocraft:markerpole and bibliocraft:clipboard

### ISSUE THREAD

**Issue by flamechair** [Nuchaz/BiblioCraft#603]
```
[20:11:39] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:markerpole
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:481) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668) ~[CraftingHelper.class:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_171]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620) [CraftingHelper.class:?]
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
> [20:11:39] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:clipboard
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:481) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822) ~[CraftingHelper.class:?]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668) ~[CraftingHelper.class:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_171]
at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620) [CraftingHelper.class:?]
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by ningaro** [comment]
Same problem

**Comment by TylerHaynie** [comment]
![image](https://user-images.githubusercontent.com/41164482/52741959-432df600-2f9c-11e9-97c1-c83b5b4b29f7.png)

sane

**Comment by KatelynAzurefire** [comment]
Still getting the same error in version 2.4.5 in Minecraft 1.12.2. I don't think it's causing any serious issues, but it's something worth considering. Here is the [PasteBin](https://pastebin.com/MQzip7qc).

**Comment by Echoweaver** [comment]
Came here to report the same thing.
