### ISSUE TITLE
Possible Leak? 

### ISSUE THREAD

**Issue by Daveanna** [Nuchaz/BiblioCraft#621]
Hi there! First off, I'd just like to say that I love this mod and can't imagine playing Minecraft without it! With that being said, I've encountered an error on my personal server, and I'm trying to pinpoint the problem. This is from the server log, and I'm not sure if the first two lines are related or not, but I thought I'd include them just in case. I've been having instability issues on the server (in the last 2 days), getting kicked out frequently and really lengthy load times on the chunks. The most recently used Bibliocraft items were the creative mode-filled bookshelves and framed shelf (covered with an iron block). 

`24.10 12:17:39 [Server] INFO Oct 24, 2018 12:17:39 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
24.10 12:17:39 [Server] INFO SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.
24.10 12:18:54 [Multicraft] Auto-saving world...
24.10 12:18:54 [Server] Server thread/INFO [minecraft/DedicatedServer]: Saving is already turned on
24.10 12:18:54 [Server] Server thread/INFO [minecraft/DedicatedServer]: Saving...
24.10 12:18:55 [Server] Server thread/INFO [minecraft/DedicatedServer]: Saved the world
24.10 12:20:35 [Server] Server thread/FATAL [minecraft/MinecraftServer]: Error executing task
24.10 12:20:35 [Server] INFO java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityBookcase.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
24.10 12:20:35 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
24.10 12:20:35 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
24.10 12:20:35 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
24.10 12:20:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
24.10 12:20:35 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
24.10 12:20:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
24.10 12:20:35 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
24.10 12:20:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
24.10 12:20:35 [Server] INFO Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityBookcase.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
24.10 12:20:35 [Server] INFO at jds.bibliocraft.tileentities.TileEntityBookcase.getStackInSlot(TileEntityBookcase.java) ~[TileEntityBookcase.class:?]
24.10 12:20:35 [Server] INFO at com.rwtema.extrautils2.crafting.Radar$PacketPing.lambda$doStuffServer$1(Radar.java:185) ~[Radar$PacketPing.class:?]
24.10 12:20:35 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
24.10 12:20:35 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
24.10 12:20:35 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
24.10 12:20:35 [Server] INFO ... 5 more`

Any help would be greatly appreciated. As far as the leak comment in the code, I don't know how to edit the JVM on a server, so in the (likely) scenario you need it, I would need to be walked through that part. Thanks in advance for the help and understanding.

**Comment by X-Niter** [comment]
Hmm interesting. I have the same issue with Biblio-craft as well. Still wondering how to resolve the issue.
