### ISSUE TITLE
Bibliocraft seems to be conflicting with Custom NPCs? java.lang.NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by lolnigga** [Nuchaz/BiblioCraft#622]
When I have both Bibliocraft and Custom NPCs installed on my server I get this crash report but everything works fine if I delete either of them.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 24.10.18 0:34
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at jds.bibliocraft.models.BiblioModelWood.func_177550_a(BiblioModelWood.java:191)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:88)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_178258_b(ForgeBlockModelRenderer.java:53)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:40)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:30)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:905)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1287)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at jds.bibliocraft.models.BiblioModelWood.func_177550_a(BiblioModelWood.java:191)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:88)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_178258_b(ForgeBlockModelRenderer.java:53)

-- Block model being tesselated --
Details:
	Block: bibliocraft:Bookcase[woodtype=Oak]
	Block location: World: (-405,71,521), Chunk: (at 11,4,9 in -26,32; contains blocks -416,0,512 to -401,255,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:40)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:30)

-- Block being tesselated --
Details:
	Block type: ID #198 (tile.BiblioCraft:Bookcase // jds.bibliocraft.blocks.BlockBookcase)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-405,71,521), Chunk: (at 11,4,9 in -26,32; contains blocks -416,0,512 to -401,255,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:94)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:194)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(SourceFile:121)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:905)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1287)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['becmoJlo4b'/111749, l='MpServer', x=-420,67, y=76,00, z=524,85]]
	Chunk stats: MultiplayerChunkCache: 10, 10
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -457,00,71,00,587,00 - World: (-457,71,587), Chunk: (at 7,4,11 in -29,36; contains blocks -464,0,576 to -449,255,591), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 5745471 game time, 435868 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 49 total; [EntityPlayerSP['becmoJlo4b'/111749, l='MpServer', x=-420,67, y=76,00, z=524,85], EntityItemFrame['entity.ItemFrame.name'/111873, l='MpServer', x=-319,50, y=125,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111872, l='MpServer', x=-319,50, y=124,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111875, l='MpServer', x=-319,50, y=120,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111874, l='MpServer', x=-319,50, y=123,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111876, l='MpServer', x=-319,50, y=126,50, z=480,97], EntitySkeleton['Скелет'/111751, l='MpServer', x=-410,50, y=28,00, z=458,50], EntityZombie['Зомби'/111750, l='MpServer', x=-432,97, y=87,00, z=454,44], EntityCreeper['Крипер'/111753, l='MpServer', x=-388,50, y=15,00, z=461,50], EntitySkeleton['Скелет'/111752, l='MpServer', x=-400,50, y=28,00, z=449,50], EntityEnderman['Эндермен'/111755, l='MpServer', x=-386,50, y=37,00, z=459,50], EntityZombie['Зомби'/111754, l='MpServer', x=-384,25, y=32,00, z=451,22], EntitySpider['Паук'/111757, l='MpServer', x=-382,50, y=32,00, z=449,50], EntitySkeleton['Скелет'/111756, l='MpServer', x=-391,50, y=70,00, z=453,50], EntityBat['Летучая мышь'/111758, l='MpServer', x=-374,09, y=38,16, z=454,66], EntityBat['Летучая мышь'/111764, l='MpServer', x=-395,47, y=23,91, z=445,13], EntityCreeper['Крипер'/111766, l='MpServer', x=-356,50, y=12,00, z=453,50], EntityBat['Летучая мышь'/111772, l='MpServer', x=-379,25, y=33,10, z=447,75], EntityItemFrame['entity.ItemFrame.name'/111789, l='MpServer', x=-321,50, y=122,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111788, l='MpServer', x=-321,50, y=123,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111791, l='MpServer', x=-320,50, y=123,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111790, l='MpServer', x=-320,50, y=122,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111793, l='MpServer', x=-321,50, y=124,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111792, l='MpServer', x=-320,50, y=124,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111795, l='MpServer', x=-322,50, y=123,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111794, l='MpServer', x=-322,50, y=124,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111797, l='MpServer', x=-320,50, y=125,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111796, l='MpServer', x=-322,50, y=122,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111799, l='MpServer', x=-322,50, y=125,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111798, l='MpServer', x=-321,50, y=125,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111801, l='MpServer', x=-323,50, y=124,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111800, l='MpServer', x=-323,50, y=125,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111803, l='MpServer', x=-323,50, y=122,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111802, l='MpServer', x=-323,50, y=123,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111805, l='MpServer', x=-321,50, y=121,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111804, l='MpServer', x=-323,50, y=121,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111807, l='MpServer', x=-320,50, y=121,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111806, l='MpServer', x=-322,50, y=121,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111809, l='MpServer', x=-321,50, y=120,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111808, l='MpServer', x=-320,50, y=120,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111811, l='MpServer', x=-323,50, y=120,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111810, l='MpServer', x=-322,50, y=120,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111813, l='MpServer', x=-322,50, y=126,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111812, l='MpServer', x=-323,50, y=126,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111815, l='MpServer', x=-320,50, y=126,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111814, l='MpServer', x=-321,50, y=126,50, z=480,97], EntitySheep['Овца'/111816, l='MpServer', x=-498,34, y=73,00, z=451,47], EntityItemFrame['entity.ItemFrame.name'/111871, l='MpServer', x=-319,50, y=122,50, z=480,97], EntityItemFrame['entity.ItemFrame.name'/111870, l='MpServer', x=-319,50, y=121,50, z=480,97]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 305270240 bytes (291 MB) / 625963008 bytes (596 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
	UCHIJA	BiblioCraft{2.0.1} [BiblioCraft] (BiblioCraft[v2.0.1][MC1.8.9].jar) 
	UCHIJA	customnpcs{1.8.9} [CustomNPCs] (CustomNpcs_1.8.9(29oct16).jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1902-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: resources.zip
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz

**Comment by lolnigga** [comment]
UPD: I've cleared the "resourcePacks" line in options.txt and, strangely enough, it worked... it's funny because I don't even have any resourcepack
