### ISSUE TITLE
Bug with RfTools Storage Scanner

### ISSUE THREAD

**Issue by Tanguygab** [Nuchaz/BiblioCraft#629]
Hello, I've got a bug with Bibliocraft and the Storage Scanner from RfTools,
When I scan a Shelf/Tool Rack (I didn't test with other container) and I wan't to craft an item in one of my other block scanned, I get this error (at the bottom):
[bug.txt](https://github.com/Nuchaz/BiblioCraft/files/2659509/bug.txt)
I also open a Issue on RfTools GitHub.

**Comment by josephcsible** [comment]
Cross-posting the important bit of the log:
```
[18:37:57] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityShelf.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityShelf.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
	at jds.bibliocraft.tileentities.TileEntityShelf.getStackInSlot(TileEntityShelf.java) ~[TileEntityShelf.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource.getStackInSlot(TileEntityItemSource.java:37) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource.access$200(TileEntityItemSource.java:16) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:118) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:89) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.tryRecipe(StorageCraftingTools.java:58) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.testCraftItems(StorageCraftingTools.java:284) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:182) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:165) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.craftFromGrid(StorageCraftingTools.java:322) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.CommandHandler.lambda$registerCommands$19(CommandHandler.java:150) ~[CommandHandler.class:?]
	at mcjty.lib.McJtyLib.handleCommand(McJtyLib.java:100) ~[McJtyLib.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.handle(PacketSendServerCommand.java:51) ~[PacketSendServerCommand$Handler.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.lambda$onMessage$0(PacketSendServerCommand.java:46) ~[PacketSendServerCommand$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[18:38:47] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityToolRack.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityToolRack.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
	at jds.bibliocraft.tileentities.TileEntityToolRack.getStackInSlot(TileEntityToolRack.java) ~[TileEntityToolRack.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource.getStackInSlot(TileEntityItemSource.java:37) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource.access$200(TileEntityItemSource.java:16) ~[TileEntityItemSource.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:118) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.TileEntityItemSource$1.next(TileEntityItemSource.java:89) ~[TileEntityItemSource$1.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.tryRecipe(StorageCraftingTools.java:58) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.testCraftItems(StorageCraftingTools.java:284) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:182) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.blocks.storagemonitor.StorageScannerTileEntity.craft(StorageScannerTileEntity.java:165) ~[StorageScannerTileEntity.class:?]
	at mcjty.rftools.craftinggrid.StorageCraftingTools.craftFromGrid(StorageCraftingTools.java:322) ~[StorageCraftingTools.class:?]
	at mcjty.rftools.CommandHandler.lambda$registerCommands$19(CommandHandler.java:150) ~[CommandHandler.class:?]
	at mcjty.lib.McJtyLib.handleCommand(McJtyLib.java:100) ~[McJtyLib.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.handle(PacketSendServerCommand.java:51) ~[PacketSendServerCommand$Handler.class:?]
	at mcjty.lib.network.PacketSendServerCommand$Handler.lambda$onMessage$0(PacketSendServerCommand.java:46) ~[PacketSendServerCommand$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by Famous5000** [comment]
Hate to necropost, but it's been 3 months... Any progress on this?

**Comment by Tanguygab** [comment]
I don't know
