### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Fridtjof-DE** [Nuchaz/BiblioCraft#631]
I get this error with Forge 1.12.2-14.23.5.2768 and BiblioCraft v2.4.5.

`[16:38:59] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:markerpole
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:481) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[16:38:59] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:clipboard
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:481) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:409) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_181]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

**Comment by C0rn3j** [comment]
Still an issue on `forge-1.12.2-14.23.5.2838`
```
[11:39:43] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:markerpole                                                                                                                                                                                                                                                                                                                                            
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed                                                                                                                                                                                                                                                                                                                                                        
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:487) ~[CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                         
        at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:415) ~[CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                              
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                  
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                              
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:676) ~[CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                            
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_222]                                                                                                                                                                                                                                                                                                                                                              
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:626) [CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                             
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]                                                                                                                                                                                                                                                                                                                                       
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]                                                                                
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]                                                                                    
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]                                                                                                                                                                                                                                                                                                                          
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]                                                                                                                                                                                                                                                                                                                                
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]                                                                                                                                                                                                                                                                                                                                                                         
[11:39:43] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:clipboard                                                                                                                                                                                                                                                                                                                                             
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed                                                                                                                                    
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:487) ~[CraftingHelper.class:?]                                                                                     
        at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:415) ~[CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                              
        at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]                                                                              
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]                                                                                          
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:676) ~[CraftingHelper.class:?]                                                                                        
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_222]                                                                                                                                          
        at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:626) [CraftingHelper.class:?]                                                                                                                                                                                                                                                                                                             
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]                                                                                                                                                                                                                                                                                                                                       
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]                                                                                                                                                                                                                                                                                                    
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]                                                                                                                                                                                                                                                                                                        
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]                                                                                                                                                                                                                                                                                                                          
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]                                                                                                                                                                                                                                                                                                                                
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]                                                                  
```
