### ISSUE TITLE
BiblioCraft breaks storage scanners

### ISSUE THREAD

**Issue by Mr-Rixa** [Nuchaz/BiblioCraft#640]
Hi!

Having a **fancy sign**, bookshelf or anything from this mod with inventory nearby beaks "Search Nearby Chests" feature from Extra Utilities 2 or any other kind of storage scanners (like rftools storage scanner)

So far this is the only mod I've found that breaks storage scanners

---
Modpack: Enigmatica 2 Expert (1.53)
Mod Version: 2.4.5
Minecraft version 1.12.2
---
Output from serverlog:
```
[21:16:17] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityFancySign.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityFancySign.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at jds.bibliocraft.tileentities.TileEntityFancySign.getStackInSlot(TileEntityFancySign.java) ~[TileEntityFancySign.class:?]
        at com.rwtema.extrautils2.crafting.Radar$PacketPing.lambda$doStuffServer$1(Radar.java:185) ~[Radar$PacketPing.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by Gunner76th** [comment]
Duplicate of https://github.com/Nuchaz/BiblioCraft/issues/671
