### ISSUE TITLE
Error while loading Server 

### ISSUE THREAD

**Issue by djdanby** [Nuchaz/BiblioCraft#672]
Tested with: Forge 2838 and 2768
Minecraft: 1.12.2
Bibliocraft: 2.4.5 and 2.4.4
Other Mods: Nothing. BiblioCraft only!

Please fix this Error. ;)

[18:42:18] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:markerpole
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:487) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:415) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:676) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_192]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:626) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
[18:42:18] [Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:clipboard
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:487) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:415) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:676) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_192]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:626) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]

**Comment by PhoenixDIE** [comment]
Yeah, i have added this mod and im getting this same error wile loading. Server still starts but this is a Error, not a warning. might be game breaking.

**Comment by Electroblade** [comment]
I love this mod, but when I add it to my mod pack, it causes a crash on loading. If I disable it the game starts fine. I will attach the crash report, hope it helps. 

[crash-2019-10-10_02.36.43-client.txt](https://github.com/Nuchaz/BiblioCraft/files/3709957/crash-2019-10-10_02.36.43-client.txt)
