### ISSUE TITLE
Parsing error loading recipe bibliocraft:clipboard

### ISSUE THREAD

**Issue by Caaruzo** [Nuchaz/BiblioCraft#674]
Getting an error on Server startup all the time

#### Affected Versions

- BiblioCraft **BiblioCraft[v2.4.5][MC1.12.2].jar**
- Minecraft: **1.12.2**
- Forge: **forge-1.12.2-14.23.5.2838-universal**
- SpongeForge? **no**
- Optifine? **no**
- Single Player and/or Server? **Server**

`[Server thread/ERROR] [FML]: Parsing error loading recipe bibliocraft:clipboard
com.google.gson.JsonSyntaxException: Invalid pattern: empty pattern not allowed
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:487) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:415) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:676) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_221]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:626) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Comment by ProsperCraft** [comment]
Same - -https://gist.github.com/ProsperCraft/0514b320d1fbacf852063b2a3a22ffc2

With BiblioCraft[v2.4.5][MC1.12.2]
