### ISSUE TITLE
Version Check fails due to 403

### ISSUE THREAD

**Issue by Chronophylos** [Nuchaz/BiblioCraft#684]
Using curl I get 200 not 403.
```
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.bibliocraftmod.com/vcheck/version.txt
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivileged(Native Method)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.net.URL.openStream(URL.java:1045)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck.getNetVersion(VersionCheck.java:58)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck$1.run(VersionCheck.java:46)
[22:19:01] [Thread-315/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by grant-mullinax** [comment]
I am having this issue as well

**Comment by addisonmartin** [comment]
I am also having this issue, with the Life in the Valley modpack. It is preventing the entire modpack from working. I am using BiblioCraft version 2.4.5.

**Comment by NathanPB** [comment]
same

**Comment by Lothrazar** [comment]
Please delete the version checker in the code.

If you really really need it forge has a built in system, just build a json file and add to your @Mod annotation for example
 ....... updateJSON** = "https://raw.githubusercontent.com/Lothrazar/Cyclic/trunk/1.12/update.json",  ....)
`

see net.minecraftforge.fml.common.Mod
