### ISSUE TITLE
Some Custom Paintings Causing Crashing [v2.4.5][MC1.12.2]

### ISSUE THREAD

**Issue by pandy351** [Nuchaz/BiblioCraft#692]
Some times when I put some paintings in they seem to crash my game when I try to add them. Here's the crash report. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BlockbusterCore (blockbuster-1.6.1-1.12.2.jar)
  FutureMC (future-mc-0.1.13.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 11/16/19 3:18 PM
Description: Initializing game

net.minecraft.client.renderer.StitcherException: Unable to fit: bibliocraft:custompaintings/bros - size: 687x687 - Maybe try a lowerresolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:70)
	at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:216)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:70)
	at net.minecraft.client.renderer.texture.TextureMap.finishLoading(TextureMap.java:216)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:112)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2001083824 bytes (1908 MB) / 4104126464 bytes (3914 MB) up to 7337410560 bytes (6997 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1177m -Xmx7871m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 37 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version               | Source                                            | Signature                                |
	|:----- |:----------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2                | minecraft.jar                                     | None                                     |
	| LCH   | mcp               | 9.42                  | minecraft.jar                                     | None                                     |
	| LCH   | FML               | 8.0.99.99             | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCH   | forge             | 14.23.5.2847          | forge-1.12.2-14.23.5.2847-universal.jar           | None                                     |
	| LCH   | srm-hooks         | 1.12.2-1.0.0          | minecraft.jar                                     | None                                     |
	| LCH   | futuremccore      | 0.1.12                | minecraft.jar                                     | None                                     |
	| LCH   | securitycraft     | v1.8.13.1             | [1.12.2]+SecurityCraft+v1.8.13.1.jar              | None                                     |
	| LCH   | architecturecraft | @VERSION@             | architecturecraft-1.12-3.98.jar                   | None                                     |
	| LCH   | bibliocraft       | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| LCH   | mclib             | 1.0.3                 | mclib-1.0.3-1.12.2.jar                            | None                                     |
	| LCH   | moreplayermodels  | 1.12.2                | MorePlayerModels_1.12.2-(29Sep19).jar             | None                                     |
	| LCH   | metamorph         | 1.1.9                 | metamorph-1.1.9-1.12.2.jar                        | None                                     |
	| LCH   | blockbuster       | 1.6.1                 | blockbuster-1.6.1-1.12.2.jar                      | None                                     |
	| LCH   | blockcraftery     | 1.12.2-1.3.1          | blockcraftery-1.12.2-1.3.1.jar                    | None                                     |
	| LCH   | ctm               | MC1.12.2-0.3.3.22     | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
	| LCH   | jei               | 4.15.0.292            | jei_1.12.2-4.15.0.292.jar                         | None                                     |
	| LCH   | chisel            | MC1.12.2-1.0.1.44     | Chisel-MC1.12.2-1.0.1.44.jar                      | None                                     |
	| LCH   | chiselsandbits    | 14.33                 | chiselsandbits-14.33.jar                          | None                                     |
	| LCH   | codechickenlib    | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | customnpcs        | 1.12                  | CustomNPCs_1.12.2-(01Oct19).jar                   | None                                     |
	| LCH   | ptrmodellib       | 1.0.4                 | PTRLib-1.0.4.jar                                  | None                                     |
	| LCH   | props             | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                        | None                                     |
	| LCH   | fairylights       | 2.1.9                 | fairylights-2.1.9-1.12.2.jar                      | None                                     |
	| LCH   | flatcoloredblocks | mc1.12-6.8            | flatcoloredblocks-mc1.12-6.8.jar                  | None                                     |
	| LCH   | cfm               | 6.3.1                 | furniture-6.3.1-1.12.2.jar                        | None                                     |
	| LCH   | minecraftfuture   | 0.1.13                | future-mc-0.1.13.jar                              | None                                     |
	| LCH   | malisiscore       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
	| LCH   | malisisdoors      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LCH   | nei               | 2.4.3                 | NotEnoughItems-1.12.2-2.4.3.245-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | harvestcraft      | 1.12.2zb              | Pam's+HarvestCraft+1.12.2zf.jar                   | None                                     |
	| LCH   | secretroomsmod    | 5.6.4                 | secretroomsmod-1.12.2-5.6.4.jar                   | None                                     |
	| LCH   | tropicraft        | 7.1.9.115             | tropicraft-MC1.12.2-7.1.9.115.jar                 | None                                     |
	| LCH   | variedcommodities | 1.12.2                | VariedCommodities_1.12.2(27oct19).jar             | None                                     |
	| LCH   | worldedit         | 6.1.10-SNAPSHOT       | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| LCH   | mysticallib       | 1.12.2-1.4.0          | mysticallib-1.12.2-1.4.0.jar                      | None                                     |
	| UD    | blockbuster_core  | 1.6.1                 | minecraft.jar                                     | None                                     |
	| UD    | mclib_core        | 1.0.3                 | minecraft.jar                                     | None                                     |

	Loaded coremods (and transformers): 
BlockbusterCore (blockbuster-1.6.1-1.12.2.jar)
  mchorse.blockbuster.core.BBCoreClassTransformer
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: NNPH Resource Pack
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz

None of the pictures are in folders, or zipped, and all use lower case letters, no spaces, no special characters, and are in the .png format. I have some other mods in the pack, and some painting do work. it's not a mod conflict, because without some painting, it runs just fine. but not all of the paintings work. All of the pictures have been looked over and nothing seems to make sense. How this painting could not work...
![lillywoodsbow](https://user-images.githubusercontent.com/57847985/69000489-58b2b200-0885-11ea-8aa8-b37119c8d276.png)

but this one does...
![leoakanightman](https://user-images.githubusercontent.com/57847985/69000471-17ba9d80-0885-11ea-8d26-59229db36465.png)

and this one does not work
![corainabubble](https://user-images.githubusercontent.com/57847985/69000490-5f412980-0885-11ea-92fa-bc1353721330.png)

but this one does. 
![yanderenyx](https://user-images.githubusercontent.com/57847985/69000476-286b1380-0885-11ea-8bbb-17a6e6b6ce06.png)

Is there something with the images that I'm not seeing or is there something more?

**Comment by LithTheKitten** [comment]
sad that it takes an year to get help

are you loading into the game with pictures around?
minecraft immedialty craps itself if you either enter the world with more than 10+ pictures closeby or approach a place with that much pictures, not even allocating ram will help with this
