### ISSUE TITLE
[Crash] Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntityArmorStand.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract

### ISSUE THREAD

**Issue by Krougal** [Nuchaz/BiblioCraft#693]
https://paste.dimdev.org/nixikadaha.mccrash

I keep getting these. I am not even interacting with the armor stand at the time. Typically in Cooking with Blockheads kitchen when it seems to happen (it is same chunk though). Armor stand is holding, Thaumcraft robes, that's it.

**Comment by Derkades** [comment]
Paste has expired, here is a new one with presumably the same error
```
[22:44:08] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntitySeat.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_282]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_282]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.AbstractMethodError: Method jds/bibliocraft/tileentities/TileEntitySeat.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
        at jds.bibliocraft.tileentities.TileEntitySeat.getStackInSlot(TileEntitySeat.java) ~[TileEntitySeat.class:?]
        at com.rwtema.extrautils2.crafting.Radar$PacketPing.lambda$doStuffServer$1(Radar.java:185) ~[Radar$PacketPing.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

For me, not a crash but shows up every so often in the log
